// v0.3 prototype. Field names mirror the live Shelf Library sheet.
const records=[
{id:"2154874253",releaseId:"28133161",artist:"9 Theory",title:"Comfort In The Orange Glow",year:2022,label:"Odyzey Music",format:"2x Vinyl (LP, Album)",folder:"Christian's Picks",rating:4,genre:"Electronic",style:"Downtempo, Trip-Hop",purchased:"New",color:"#58747d"},
{id:"2161410494",releaseId:"93640",artist:"A Tribe Called Quest",title:"People's Instinctive Travels And The Paths Of Rhythm",year:1996,label:"Jive",format:"2x Vinyl (LP, Album, Reissue, Remastered)",folder:"Shante's Picks",rating:5,genre:"Hip-Hop",style:"Jazzy Hip-Hop / Conscious",purchased:"Pre-Owned - Opened",color:"#776b58"},
{id:"2164610456",releaseId:"8003028",artist:"A Tribe Called Quest",title:"Midnight Marauders",year:2015,label:"Jive",format:"1x Vinyl (LP, Album, Reissue)",folder:"Shante's Picks",rating:5,genre:"Hip-Hop",style:"Jazzy Hip-Hop / Boom Bap",purchased:"Pre-Owned - Opened",color:"#76594e"},
{id:"2022297123",releaseId:"4504875",artist:"Akron/Family",title:"Sub Verses",year:2013,label:"Dead Oceans",format:"2x Vinyl (LP, 45 RPM)",folder:"Outgoing",rating:0,genre:"Rock",style:"Indie Rock",purchased:"New",color:"#4d5963"},
{id:"2154874644",releaseId:"25424551",artist:"Emby Alexander",title:"SOARS ERA",year:2022,label:"Earth Libraries",format:"1x Vinyl (LP)",folder:"Christian's Picks",rating:0,genre:"Rock",style:"Indie Rock",purchased:"New",color:"#704a4d"},
{id:"1609023751",releaseId:"1313001",artist:"America",title:"History - America's Greatest Hits",year:1975,label:"Warner Bros. Records",format:"1x Vinyl (LP, Compilation, Stereo)",folder:"Christian's Picks",rating:3,genre:"Rock",style:"Folk Rock",purchased:"Pre-Owned - Opened",color:"#745e37"},
{id:"2160468790",releaseId:"37602669",artist:"Angine De Poitrine",title:"Vol.1",year:2026,label:"Spectacles Bonzaï",format:"1x Vinyl (LP, Album, Reissue, Repress, Stereo)",folder:"Christian's Picks",rating:3,genre:"Rock",style:"Math Rock",purchased:"Pre-Owned - Opened",color:"#584a3c"}
];
let state=JSON.parse(localStorage.getItem("vj-state-v03")||"null")||{selected:records[0].id,queue:[],plays:[],art:{},filters:{genre:"",style:"",decade:"",folder:""}};
const $=id=>document.getElementById(id), rec=id=>records.find(r=>r.id===id), save=()=>localStorage.setItem("vj-state-v03",JSON.stringify(state));
function toast(s){$("toast").textContent=s;setTimeout(()=>$("toast").textContent="",2200)}
function artStyle(r){return state.art[r.id]?`url('${state.art[r.id]}')`:`linear-gradient(145deg,${r.color},#171713)`}
function art(el,r){el.style.background=artStyle(r);el.textContent=state.art[r.id]?"":r.title}
async function resolveArt(r){if(state.art[r.id]!==undefined)return;try{let q=encodeURIComponent(`${r.artist} ${r.title}`);let res=await fetch(`https://itunes.apple.com/search?term=${q}&entity=album&limit=8`);let j=await res.json();let hit=j.results.find(x=>x.collectionName?.toLowerCase()===r.title.toLowerCase())||j.results[0];state.art[r.id]=hit?.artworkUrl100?.replace("100x100bb","600x600bb")||""}catch(e){state.art[r.id]=""}save();renderAll(false)}
function resolveVisibleArt(){records.forEach(resolveArt)}
function playCount(id){return state.plays.filter(p=>p.id===id).length}
function renderHome(){let r=rec(state.selected)||records[0];art($("albumArt"),r);$("albumTitle").textContent=r.title;$("albumArtist").textContent=r.artist;$("albumMeta").textContent=`${r.year} • ${r.genre} • ${r.style}`;let n=playCount(r.id);$("playInfo").textContent=n?`Played ${n} time${n===1?"":"s"}`:"Not played yet";$("queueBadge").textContent=state.queue.length;$("queuePreview").innerHTML=state.queue.length?state.queue.map(id=>{let q=rec(id);return `<div class="queue-card" data-id="${id}"><div class="mini-art" style="background:${artStyle(q)}">${state.art[q.id]?"":q.artist[0]}</div><div class="row-text"><strong>${q.title}</strong><span>${q.artist}</span></div></div>`}).join(""):`<p class="meta">Queue is empty. Pick something good.</p>`;document.querySelectorAll("#queuePreview .queue-card").forEach(x=>x.onclick=()=>{setQueueDrawer(false);select(x.dataset.id)})}
function select(id){state.selected=id;save();renderAll();show("home")}
function setQueueDrawer(open){
  $("queueDrawer").classList.toggle("open",open);
  $("queueScrim").classList.toggle("open",open);
  $("queueDrawer").setAttribute("aria-hidden",String(!open));
  $("queueDrawerToggle").setAttribute("aria-expanded",String(open));
}
$("queueDrawerToggle").onclick=()=>setQueueDrawer(true);
$("queueDrawerClose").onclick=()=>setQueueDrawer(false);
$("queueScrim").onclick=()=>setQueueDrawer(false);
$("openFullQueueBtn").onclick=()=>{setQueueDrawer(false);show("queue")};
function addQueue(id){if(!state.queue.includes(id)){state.queue.push(id);save();renderAll();toast("Added to queue")}else toast("Already in queue")}
$("finishBtn").onclick=()=>{let r=rec(state.selected);state.plays.unshift({id:r.id,at:new Date().toISOString()});state.queue=state.queue.filter(id=>id!==r.id);save();renderAll();toast(`Logged: ${r.artist} — ${r.title}`)};$("queueCurrentBtn").onclick=()=>addQueue(state.selected);$("pickBtn").onclick=()=>openPicker();$("clearQueueBtn").onclick=()=>{state.queue=[];save();renderAll()};
function filteredRecords(){let f=$("search").value.toLowerCase().trim(),x=state.filters;let rows=records.filter(r=>(r.artist+" "+r.title+" "+r.genre+" "+r.style).toLowerCase().includes(f)&&(!x.genre||r.genre===x.genre)&&(!x.style||r.style.includes(x.style))&&(!x.decade||Math.floor(r.year/10)*10===+x.decade)&&(!x.folder||r.folder===x.folder));let sort=$("sort").value;rows.sort((a,b)=>sort==="title"?a.title.localeCompare(b.title):sort==="yearDesc"?b.year-a.year:sort==="ratingDesc"?b.rating-a.rating:a.artist.localeCompare(b.artist));return rows}
function renderCollection(){let rows=filteredRecords();$("collectionCount").textContent=`${rows.length} RECORDS`;let active=Object.entries(state.filters).filter(([,v])=>v).map(([k,v])=>`${k}: ${v}`);$("activeFilters").textContent=active.length?active.join("  •  "):"";$("collectionGrid").innerHTML=rows.map(r=>`<div class="album-card" data-id="${r.id}"><div class="cover" style="background:${artStyle(r)}">${state.art[r.id]?"":r.title}</div><strong>${r.title}</strong><span>${r.artist}</span></div>`).join("");document.querySelectorAll(".album-card").forEach(x=>x.onclick=()=>openDetail(x.dataset.id))}
$("search").oninput=renderCollection;$("sort").onchange=renderCollection;$("filterBtn").onclick=openFilters;$("randomResultsBtn").onclick=()=>{let pool=filteredRecords();if(pool.length)showRecommendation(pool,"Filtered collection")};
function renderQueue(){$("queueCount").textContent=`${state.queue.length} RECORDS`;$("queueList").innerHTML=state.queue.length?state.queue.map((id,i)=>{let r=rec(id);return `<div class="list-row"><div class="mini-art" style="background:${artStyle(r)}">${i+1}</div><div class="row-text"><strong>${r.title}</strong><span>${r.artist}</span></div><div class="queue-controls"><button data-up="${i}">↑</button><button data-down="${i}">↓</button><button data-play="${id}">PLAY</button><button class="danger" data-remove="${i}">×</button></div></div>`}).join(""):`<p class="meta">Nothing queued yet.</p>`;document.querySelectorAll("[data-play]").forEach(x=>x.onclick=()=>select(x.dataset.play));document.querySelectorAll("[data-remove]").forEach(x=>x.onclick=()=>{state.queue.splice(+x.dataset.remove,1);save();renderAll()});document.querySelectorAll("[data-up]").forEach(x=>x.onclick=()=>moveQueue(+x.dataset.up,-1));document.querySelectorAll("[data-down]").forEach(x=>x.onclick=()=>moveQueue(+x.dataset.down,1))}
function moveQueue(i,d){let j=i+d;if(j<0||j>=state.queue.length)return;[state.queue[i],state.queue[j]]=[state.queue[j],state.queue[i]];save();renderAll()}
function renderStats(){let counts={};state.plays.forEach(p=>{let r=rec(p.id);if(r)counts[r.artist]=(counts[r.artist]||0)+1});$("totalPlays").textContent=state.plays.length;$("uniquePlayed").textContent=new Set(state.plays.map(p=>p.id)).size;$("topArtist").textContent=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0]?.[0]||"—";$("historyList").innerHTML=state.plays.slice(0,8).map(p=>{let r=rec(p.id);return r?`<div class="list-row"><div class="row-text"><strong>${r.artist} — ${r.title}</strong><span>${new Date(p.at).toLocaleString()}</span></div></div>`:""}).join("")||`<p class="meta">No plays logged yet.</p>`}
function modal(html){$("modalBody").innerHTML=html;$("modal").classList.remove("hidden")}function closeModal(){$("modal").classList.add("hidden")}$("modalClose").onclick=closeModal;$("modal").onclick=e=>{if(e.target===$("modal"))closeModal()}
function openDetail(id){let r=rec(id),n=playCount(id);modal(`<div class="detail"><div class="detail-cover" style="background:${artStyle(r)}">${state.art[r.id]?"":r.title}</div><div><div class="eyebrow">ALBUM DETAILS</div><h2>${r.title}</h2><p class="artist">${r.artist}</p><p class="meta">${r.year} • ${r.label}<br>${r.genre} • ${r.style}<br>${r.format}<br>${r.folder} • ${r.rating?"★".repeat(r.rating):"Unrated"}<br>${n?`Played ${n} time${n===1?"":"s"}`:"Never played"}</p><div class="modal-actions"><button class="primary" id="detailPlay">PLAY NOW</button><button id="detailQueue">ADD TO QUEUE</button></div></div></div>`);$("detailPlay").onclick=()=>{closeModal();select(id)};$("detailQueue").onclick=()=>{addQueue(id);closeModal()}}
function unique(k){return [...new Set(records.map(r=>r[k]).filter(Boolean))].sort()}
function openFilters(){let genres=unique("genre"),styles=[...new Set(records.flatMap(r=>r.style.split(/, | \/ /)))].sort(),decades=[...new Set(records.map(r=>Math.floor(r.year/10)*10))].sort(),folders=unique("folder");modal(`<div class="eyebrow">COLLECTION</div><h2>FILTERS</h2>${filterGroup("genre",genres)}${filterGroup("style",styles)}${filterGroup("decade",decades.map(x=>x+"s"),decades)}${filterGroup("folder",folders)}<div class="modal-actions"><button class="primary" id="applyFilters">APPLY</button><button id="clearFilters">CLEAR ALL</button></div>`);document.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>{let k=b.dataset.filter,v=b.dataset.value;state.filters[k]=state.filters[k]===v?"":v;document.querySelectorAll(`[data-filter='${k}']`).forEach(x=>x.classList.toggle("active",state.filters[k]===x.dataset.value))});$("applyFilters").onclick=()=>{save();closeModal();renderCollection()};$("clearFilters").onclick=()=>{state.filters={genre:"",style:"",decade:"",folder:""};save();closeModal();renderCollection()}}
function filterGroup(k,labels,values=labels){return `<h3>${k.toUpperCase()}</h3><div class="chips">${labels.map((x,i)=>`<button class="chip ${state.filters[k]===String(values[i])?"active":""}" data-filter="${k}" data-value="${values[i]}">${x}</button>`).join("")}</div>`}
function secureIndex(n){if(n<=1)return 0;let a=new Uint32Array(1),limit=Math.floor(0x100000000/n)*n;do crypto.getRandomValues(a);while(a[0]>=limit);return a[0]%n}
function securePick(pool){return pool[secureIndex(pool.length)]}
function openPicker(){modal(`<div class="eyebrow">PICK SOMETHING</div><h2>What kind of pick?</h2><div class="choice-grid"><button class="choice" id="surprise">SURPRISE ME<small>Truly random. No recommendation logic.</small></button><button class="choice" id="genrePick">GENRE / STYLE<small>Choose a musical lane.</small></button><button class="choice" id="vibePick">VIBE<small>Prototype mood choices.</small></button><button class="choice" id="deepPick">DIG DEEPER<small>Never played, neglected, or old favorite.</small></button></div>`);$("surprise").onclick=()=>showRecommendation(records,"Surprise Me",true);$("genrePick").onclick=chooseGenre;$("vibePick").onclick=chooseVibe;$("deepPick").onclick=chooseDepth}
function chooseGenre(){let gs=unique("genre");modal(`<div class="eyebrow">GENRE / STYLE</div><h2>Choose a genre</h2><div class="chips">${gs.map(g=>`<button class="chip" data-g="${g}">${g}</button>`).join("")}</div>`);document.querySelectorAll("[data-g]").forEach(b=>b.onclick=()=>chooseDepth(records.filter(r=>r.genre===b.dataset.g),b.dataset.g))}
const vibeMap={"CHILL":["Downtempo","Trip-Hop","Folk"],"ENERGETIC":["Math Rock","Boom Bap"],"HEAD-NOD":["Hip-Hop","Boom Bap","Jazzy"],"BACKGROUND":["Downtempo","Folk Rock"]};
function chooseVibe(){modal(`<div class="eyebrow">VIBE</div><h2>Choose a vibe</h2><div class="chips">${Object.keys(vibeMap).map(v=>`<button class="chip" data-v="${v}">${v}</button>`).join("")}</div><p class="meta">Vibe tags are prototype-only for now; the Sheet does not yet store them.</p>`);document.querySelectorAll("[data-v]").forEach(b=>b.onclick=()=>{let terms=vibeMap[b.dataset.v];let pool=records.filter(r=>terms.some(t=>(r.genre+" "+r.style).includes(t)));showRecommendation(pool.length?pool:records,`Vibe: ${b.dataset.v}`)})}
function chooseDepth(base=records,label="Whole collection"){if(!Array.isArray(base))base=records;modal(`<div class="eyebrow">DIG DEEPER</div><h2>Refine the pick</h2><p class="match-count">Starting pool: ${base.length} records • ${label}</p><div class="choice-grid"><button class="choice" data-depth="any">ANYTHING<small>No play-history filter.</small></button><button class="choice" data-depth="lately">HAVEN'T PLAYED LATELY<small>Oldest or never-played records.</small></button><button class="choice" data-depth="never">NEVER PLAYED<small>Only records with zero logged plays.</small></button><button class="choice" data-depth="favorite">OLD FAVORITE<small>Rated 4–5 stars and previously played.</small></button></div>`);document.querySelectorAll("[data-depth]").forEach(b=>b.onclick=()=>{let pool=depthPool(base,b.dataset.depth);showRecommendation(pool.length?pool:base,`${label} • ${b.textContent.trim()}`)})}
function depthPool(base,d){if(d==="never")return base.filter(r=>!playCount(r.id));if(d==="favorite")return base.filter(r=>r.rating>=4&&playCount(r.id));if(d==="lately"){let last={};state.plays.forEach(p=>{if(!last[p.id])last[p.id]=new Date(p.at).getTime()});let played=base.filter(r=>last[r.id]).sort((a,b)=>last[a.id]-last[b.id]);let never=base.filter(r=>!last[r.id]);return never.concat(played.slice(0,Math.max(1,Math.ceil(played.length/2))))}return base}
function showRecommendation(pool,label,isPureRandom=false){if(!pool.length)return;let r=securePick(pool);modal(`<div class="recommend-result"><div class="eyebrow">${isPureRandom?"🎲 RANDOM DRAW":"RECOMMENDATION"}</div><div class="recommend-cover" style="background:${artStyle(r)}">${state.art[r.id]?"":r.title}</div><h2>${r.title}</h2><p class="artist">${r.artist}</p><p class="match-count">${label} • ${pool.length} eligible record${pool.length===1?"":"s"}${isPureRandom?` • draw #${pool.indexOf(r)+1} of ${pool.length}`:""}</p><div class="modal-actions" style="justify-content:center"><button class="primary" id="recPlay">PLAY NOW</button><button id="recQueue">ADD TO QUEUE</button><button id="reroll">NAH, TRY AGAIN</button></div></div>`);$("recPlay").onclick=()=>{closeModal();select(r.id)};$("recQueue").onclick=()=>addQueue(r.id);$("reroll").onclick=()=>showRecommendation(pool,label,isPureRandom)}
function renderAll(loadArt=true){renderHome();renderCollection();renderQueue();renderStats();if(loadArt)resolveVisibleArt()}function show(id){document.querySelectorAll(".screen").forEach(s=>s.classList.toggle("active",s.id===id));document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.screen===id))}document.querySelectorAll(".nav-btn").forEach(b=>b.onclick=()=>show(b.dataset.screen));function tick(){$("clock").textContent=new Date().toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}setInterval(tick,1000);tick();renderAll();if("serviceWorker" in navigator&&location.protocol.startsWith("http"))navigator.serviceWorker.register("sw.js");
